const stockItems = [
  {
    id: 1,
    nombre: "Camiseta Argentina",
    cantidad: 1,
    precio: 1000,
    img: "./img/camisetaargentina.jpg",
  },
  {
    id: 2,
    nombre: "Pantalon tiro 21 adidas",
    cantidad: 1,
    precio: 1000,
    img: "./img/pantalon tiro 21.jpg",
  },
  {
    id: 3,
    nombre: "Zapatilla samba OG",
    cantidad: 1,
    precio: 1000,
    img: "./img/zapatilla samba OG.jpg",
  },
  {
    id: 4,
    nombre: "Camiseta River Plate",
    cantidad: 1,
    precio: 1000,
    img: "./img/camiseta River Plate.jpg",
  },
  {
    id: 5,
    nombre: "Buzo essentials",
    cantidad: 1,
    precio: 1000,
    img: "./img/buzo essentials.jpg",
  },
  {
    id: 6,
    nombre: "Mochila Players",
    cantidad: 1,
    precio: 1000,
    img: "./img/mochila players.jpg",
  },
  {
    id: 7,
    nombre: "Short aeroreadya",
    cantidad: 1,
    precio: 1000,
    img: "./img/short aeroready.jpg",
  },
  {
    id: 8,
    nombre: "Pelota ucl league",
    cantidad: 1,
    precio: 1000,
    img: "./img/pelota ucl league.jpg",
  },
  {
    id: 9,
    nombre: "Pantalon tiro 21",
    cantidad: 1,
    precio: 1000,
    img: "./img/pantalon tiro 21.jpg",
  },
];
